### ISSUE TITLE
What are our thoughts on ssh?

### ISSUE THREAD

**Issue by colelawrence** [silverwind/droppy#102]
Is droppy having ssh capabilities something we would consider? (As in being able to execute commands through the browser like runnable or cloud9)

The reason for having ssh capabilities would mostly be for those who wish to use droppy as their primary development environment.

**Comment by EnMod** [comment]
About the slow backend of ownCloud...would the reason my droppy install is basically freezing be because I have it running on an RPi 2? And Droppy needs to access a very large drive? I was thinking the initial directory caching was supposed to handle that.

**Comment by silverwind** [comment]
It is actually caused by the initial caching. On startup, droppy reads alle files into memory and only reads/writes the real file system when necessary. The upside is that browsing through directories is nearly instantaneous, while the downside is that a big number of files lead to a huge startup time, and it can even run out of memory when millions of files are present, apparently.

I'll think about adding a something like a `nocache` option which does skip this caching as well as folder size calculations for cases like yours.

**Comment by EnMod** [comment]
That sounds like a great idea, especially on low-memory systems.
