### ISSUE TITLE
Pasting screenshots?

### ISSUE THREAD

**Issue by sporkman** [silverwind/droppy#308]
Is that supported and if not, how hard is that?  I've noticed a number of sharing sites now allow you to paste clipboard data (that for example, has an image in it, like a screenshot) rather than saving a screenshot, selecting the file, uploading.  Instead it's browse to site, hit paste shortcut, get link.

**Comment by silverwind** [comment]
Good idea, certainly worth exploring. I'm thinking of presenting a dialog when something is pasted (both text or image), where one can choose a filename and format if it's raw text or a image. If a file is pasted directly, I think a immediate upload should be possible.

**Comment by sporkman** [comment]
That would be awesome. I was googling last night because I was curious about just how this worked, and this seems to be one of the more definitive answers with great examples: https://stackoverflow.com/questions/2176861/javascript-get-clipboard-data-on-paste-event-cross-browser
This also looks great: https://clipboardjs.com/
And Pasteboard.co code is here, which might have some interesting info: https://github.com/JoelBesada/pasteboard

**Comment by silverwind** [comment]
I tried https://github.com/layerssss/paste.js, but couldn't get it to work. I think I can do without a library in this case, it's all about handling the `paste` event properly, and I can likely re-use some already existing code that handles drag and drop.

**Comment by silverwind** [comment]
Decided to use paste.js after I noticed that it's quite hard to get this right in a cross-browser fashion. I'll rewrite this later to be more lightweight.

I'm also not quite happy with the dependency on jQuery that library brings and the performance when pasting large amounts of text is quite bad because of what I assume is caused by the base64 conversion that paste.js does, which I don't really need.

When pasting a image or text, it is automatically uploaded with a generic file name:

<img width="451" src="https://user-images.githubusercontent.com/115237/27004782-e38726a0-4e0f-11e7-97a6-b85eb593183b.png">

Pasting files is currently not really possible cross-browser, see https://github.com/layerssss/paste.js/issues/43#issuecomment-307572811.

**Comment by silverwind** [comment]
Actually changed it to not use that library as it was causing issues when creating new files. This isn't compatible with Safari, but I'll try something else there later.

https://github.com/silverwind/droppy/commit/e9ed1e1e205471cf3e518bd1195e3ad7010fb9d9

On the upside, text pasting is now much faster too :)
