### ISSUE TITLE
Can't login on created users (in docker container)

### ISSUE THREAD

**Issue by Gmousse** [silverwind/droppy#312]
Hi,
I have installed droppy with a custom DockerFile (I use arm64v8/alpine:latest as base for my raspberry).
I start it with a docker-compose up, and anything seems ok and I can assess to the login page.

But, if I add a user (I use a `docker exec -it droppy sh` and then `droppy add test 123`), and try to login on the interface, it just doesn't work.
Indeed the login api send a 401 and I can't see specials errors in the logs.

Any ideas ?

EDIT: With a `droppy list` inside the container, I can see the created users.

**Comment by silverwind** [comment]
Did you restart the container after adding the user?

**Comment by Gmousse** [comment]
Yes I tried to stop the container and then restart it but nothing happened.
I will retry later. If it doesn t work I will try to recreate the container.

Indeed, it could be a good feature to reload the user database on user modifications.

**Comment by silverwind** [comment]
Made some progress on this. The issue with the CLI not working was partly because the configuration location is different in the container, so for that to work, you'd have had to use `droppy -c /config add user pass` command. I've symlinked these directories now so it works without the switch.

There's one remaining issue: When no user exists, the first login should create a new user. This is working fine outside a container but not inside. I can hopefully check that out tomorrow.

**Comment by Gmousse** [comment]
Ok I will try the `droppy -c /config add user pass` this night.
Thanks for this fast solution.

**Comment by Gmousse** [comment]
I can confirm the `/config` behaviour. Tell me if you need some help to test your development branch.
Thanks

**Comment by silverwind** [comment]
> Tell me if you need some help to test your development branch.

I don't think that will be necessary, should be all fixed now. v6.6.2 will be released in a few minute with those fixes.
