### ISSUE TITLE
Sometimes folders are not shown

### ISSUE THREAD

**Issue by mhdev90** [silverwind/droppy#345]
Hi,

Sometimes we have a strage issue. I try to explain this issue:

We create five folders using droppy (all shown), after a few hours only two of five folders are present inside droppy, but if i take a look at the filesystem all five folders are present.

Filesystem:
```
├── stadtbezirksstatistik
├── wahlstatistik
├── wahlstatistik_(1.wg)
├── wahlstatistik2017_bt
└── wahlstatistik2018_ob_wg1
```

Droppy:
```
├── stadtbezirksstatistik
└── wahlstatistik
```

Missing:
- wahlstatistik_(1.wg)
- wahlstatistik2017_bt
- wahlstatistik2018_ob_wg1

Maybe a problem with underscores?

Droppy-Version: "droppy 8.0.4"

**Comment by silverwind** [comment]
Sorry for the late response. I tested with your filenames but couldn't reproduce. Generally, all filenames including Unicode are supported, so that shouldn't be it.

What kind of file system is the files directory on? If it is a network drive, you might need to set `pollingInterval` to something like `10000` (to scan new files every 10s) because change detection mechanisms can be unreliable on those.

**Comment by mhdev90** [comment]
Hi, no problem ;)
The files are stored on an NFS-Share but since Droppy 9.0.x the problem seems to be fixed.

**Comment by silverwind** [comment]
Okay, I'd definately recommend setting a `pollingInterval` with NFS.
